[book]
title = "Rust Problem-Solving Handbook (TH)"
authors = ["Suradet Pratomsak"]
language = "th"
description = "คู่มือแก้ปัญหา Rust Programming ภาษาไทย"

[output.html]
site-url = "https://pharmacist-sabot.github.io/rust-problem-solving/"
git-repository-url = "https://github.com/pharmacist-sabot/rust-problem-solving"
additional-css = ["theme/custom.css"]
default-theme = "ayu"

[output.html.playground]
editable = true
line-numbers = true
